name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev, main, feat/**, ci/test, test/**]
  pull_request:
    branches: [dev, main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  deploy: 
    if: ${{ contains(github.actor, 'zhangyuang') && github.ref_name == 'main' && contains(github.event.head_commit.message, 'deploy example')}}
      
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: npx esno scripts/deploy.ts
        env:
          CI: true
          SERVERLESS_DEPLOY_AK: ${{ secrets.SERVERLESS_DEPLOY_AK }}
          SERVERLESS_DEPLOY_ENDPOINT: ${{ secrets.SERVERLESS_DEPLOY_ENDPOINT }}
          SERVERLESS_DEPLOY_ID: ${{ secrets.SERVERLESS_DEPLOY_ID }}
          SERVERLESS_DEPLOY_SECRET: ${{ secrets.SERVERLESS_DEPLOY_SECRET }}
          SERVERLESS_DEPLOY_TIMEOUT: ${{ secrets.SERVERLESS_DEPLOY_TIMEOUT }}